platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/maven-yarnpkg
    tag: latest
inputs:
  - name: repo
  - name: utils
  - name: m2
run:
  path: bash
  args:
  - -c
  - |
    utils/scripts/add-repos-in-pom-xml.sh repo && \
    utils/scripts/mvn.sh "test-compile failsafe:integration-test failsafe:verify" repo
params:
  _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom